### ISSUE TITLE
tag bug fix release

### ISSUE THREAD

**Issue by musm** [JuliaInterop/MATLAB.jl#107]
cc: @ChrisRackauckas 
 (not sure if attobot is installed)
bug fixes: matlab home path finding on osx
others: depwarns on 0.6

**Comment by musm** [comment]
can also wait until 0.6 alpha

**Comment by musm** [comment]
bump

**Comment by ChrisRackauckas** [comment]
Is this repo setup with autobot?

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/8253

**Comment by musm** [comment]
thanks!
