### ISSUE TITLE
Unable to suppress output with `@matlab`

### ISSUE THREAD

**Issue by dpsanders** [JuliaInterop/MATLAB.jl#109]
I seem to be unable to suppress output with `@matlab`:

```jl
julia v0.5> @matlab v=[1 2 3];
>>
v =

     1     2     3
```

**Comment by musm** [comment]
yes  the output is `print("output from matlab in string form")`  using `;` will not suppress the formatted string output

**Comment by dpsanders** [comment]
It would be great to be able to suppress output, eg for benchmarking
purposes.

Is there any way to do so?

On 29 Mar 2017 2:09 p.m., "Mus M" <notifications@github.com> wrote:

yes the output is print("output from matlab in string form") using ; will
not suppress the formatted string output

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaInterop/MATLAB.jl/issues/109#issuecomment-290175165>,
or mute the thread

**Comment by simonster** [comment]
The easy way us to use the `mat` string literal instead of the `@matlab` macro. We should probably deprecate the latter.

**Comment by dpsanders** [comment]
OK thanks.

**Comment by musm** [comment]
also for benchmarking it's better to use `tic; toc` within the matlab script and extract the time value, otherwise you may be benchmarking calling overhead.

**Comment by dpsanders** [comment]
Good idea, thanks.

**Comment by musm** [comment]
close ?

**Comment by musm** [comment]
bumping the close part
