### ISSUE TITLE
Error "jvalue not defined" - Ubuntu

### ISSUE THREAD

**Issue by milannnnn** [JuliaInterop/MATLAB.jl#122]
For some reason an optimization script, that runs perfectly in Windows 10, throws me a "jvalue not defined" error in Ubuntu 17.10 when calling the jvalue() function. All other functions (mxarray(), jarray(),...) work perfectly in Ubuntu, except the jvalue() function.

Does anyone know what might be the problem?

Thanks ;)

**Comment by musm** [comment]
Try `Pkg.update` first

**Comment by milannnnn** [comment]
I tried updating, removing and installing again, but it doesn't help.

**Comment by musm** [comment]
What does Pkg.status say? and which julia version

**Comment by milannnnn** [comment]
Oh damn, for some reason Ubuntu installed Julia 0.4.7. I'll update it and get back :bulb: 

Thanks a lot :+1:

**Comment by musm** [comment]
Great, that's what I thought. NP
