### ISSUE TITLE
pass function name

### ISSUE THREAD

**Issue by montyvesselinov** [JuliaInterop/MATLAB.jl#124]
How the name of the function to be called can be passed? The following fails:

```
a = "plot"
@MATLAB.mat_str("$a(x, sin(x))")
```

**Comment by musm** [comment]
it's as simple as
```julia
x = linspace(-10., 10., 500)
mat"plot($x, sin($x))"  
```

**Comment by musm** [comment]
And for the function name
```julia
julia> x = linspace(-10., 10., 500)
julia> p = "plot"
julia> eval_string("$p($x);")
```

**Comment by montyvesselinov** [comment]
Very cool! Thank you very much! it works!

-monty

**Comment by musm** [comment]
Thanks don't hesitate to ask more questions / or ask for features / suggestions etc.
