### ISSUE TITLE
Problems with dynamic libraries with Matlab in osx

### ISSUE THREAD

**Issue by rharper2** [JuliaInterop/MATLAB.jl#13]
Hi, I was getting an error relating to not being able to find the dynamic libraries in matlab when I issued the using MATLAB command.

I think it was to do with the fact that although the correct lopen command was being issued for libmx.dylib (with the full library path being specified), when libmx was trying to open libtbb.dylib it was using just the "raw" name. Since we weren't in the Matlab.app per se it was failing to find it.

My (inelegant) work around was to edit the julia script (/Applications/julia.app/Contents/Resources/script) to include the correct DYLD_FALLBACK_LIBRARY_PATH, which works.

(Using DYLD_LIBRARY_PATH causes Julia to stop working).

**Comment by musm** [comment]
Is this still an issue?

**Comment by musm** [comment]
can someone close this, thanks
