### ISSUE TITLE
Installing a new version of MATLAB

### ISSUE THREAD

**Issue by albertas-jn** [JuliaInterop/MATLAB.jl#131]
I would like to share my experience with installing a new version of MATLAB (Ubuntu 16.04). From what I understood, MATLAB path is determined by `which matlab` during precompilation, which returns a path to a particular version. If a new version of MATLAB is installed, it will not be automatically picked up if the precompiled module already exists, unless you force recompilation with Base.compilecache("MATLAB"). I am suggesting that either this should be documented, or perhaps a symlink to MATLAB installation could be used instead.

**Comment by musm** [comment]
We could always query  during `init` and if detect a mismatch recompile with the new matlab version
