### ISSUE TITLE
Expand OSX search to include Student version.

### ISSUE THREAD

**Issue by rharper2** [JuliaInterop/MATLAB.jl#14]
The search in /Applications doesn't match the student version e.g. MATLAB_R2012a_Student.

Easily worked around by changing the app name.

**Comment by musm** [comment]
Is the student version the same as the academic version? I don't see the prefix?

**Comment by musm** [comment]
can someone close this, thanks

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
I think we should close, since there hasn't been any updates thanks

**Comment by musm** [comment]
bump for the close
