### ISSUE TITLE
Calling a user-defined Matlab function

### ISSUE THREAD

**Issue by Magalame** [JuliaInterop/MATLAB.jl#148]
Hi!

I have this function I wrote in a `.m` file, and I was wondering if there was a way to call it from Julia?

Thanks!

**Comment by musm** [comment]
yes read the readme

**Comment by Magalame** [comment]
I read it but I think I'm confused then. What I look for seem to be `mxcall`, but it seemed that it could call only native Matlab functions? Because there is no indication on how to tell `mxcall` what file to look into to find the function.

**Comment by musm** [comment]
first navigate to the folder where the M file is located and start julia from there so matlab finds the function. otherwise you have to add the folder to the matlab search path.

you can easily do this with the matlab string macro

**Comment by Magalame** [comment]
Thanks!

**Comment by musm** [comment]
no problem
