### ISSUE TITLE
UndefRefError after upgrading Matlab

### ISSUE THREAD

**Issue by bantin** [JuliaInterop/MATLAB.jl#152]
I just upgraded to Matlab 2018b. I changed my MATLAB_HOME environment variable to the new path, and I can confirm that Julia can see the new path, because running `get(ENV, "MATLAB_HOME", "")` returns `"/Applications/MATLAB_R2018b.app"` as expected.

However, I can't access any functionality from MATLAB.jl. Simply running `@mput` with any variable gives the following error. 

```
julia> @mput a
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] (::getfield(MATLAB, Symbol("##MSession#11#12")))(::String, ::Type, ::Int64) at /Users/Bantin/.julia/packages/MATLAB/SljED/src/engine.jl:26
 [2] Type at /Users/Bantin/.julia/packages/MATLAB/SljED/src/engine.jl:23 [inlined] (repeats 2 times)
 [3] get_default_msession at /Users/Bantin/.julia/packages/MATLAB/SljED/src/engine.jl:88 [inlined]
 [4] put_variable(::Symbol, ::Int64) at /Users/Bantin/.julia/packages/MATLAB/SljED/src/engine.jl:159
 [5] top-level scope at none:0
```

I'm using Julia 1.0 on Mac OSX Yosemite.

**Comment by musm** [comment]
which matlab.jl version  ?

**Comment by musm** [comment]
Try first
`pkg> up`
then test and if that doesn't work, try
`pkg> build MATLAB`

**Comment by bantin** [comment]
Hi @musm,

I'm using matlab.jl v0.7.1.

Running the test gives the following error:
```
ERROR: LoadError: InitError: MATLAB.jl built with version at exec /Applications/MATLAB_R2014a.app/bin/matlab, but detected new installation at exec /Applications/MATLAB_R2018b.app/bin/matlab.
Run `import Pkg; Pkg.build("MATLAB")` and restart Julia.
```

However, after following the instructions by building the package and  restarting Julia, I still get the same error when I run the test.

**Comment by musm** [comment]
did you restart julia?

**Comment by bantin** [comment]
Yes, I did restart Julia but that didn't fix it.

What did fix it was the following: I removed the package using `Pkg.rm` and also removed all of the associated .jl files. Then I re-added the package using Pkg. Now the tests pass.

I think the issue then is that maybe running Pkg.build and restarting Julia doesn't always resolve the InitError, but this might be a special case because I updated my MATLAB version. Either way, feel free to close the issue if you don't think it needs any action.

**Comment by musm** [comment]
very strange, updating matlab and running `pkg> build MATLAB` should have updated the old reference

**Comment by musm** [comment]
Ok I think I see the issue `build MATLAB` doesn't update the precompile cache.

**Comment by OVGULIU** [comment]
@musm

 the same issue now ..............

**Comment by sadda** [comment]
What solved this issue for me was

`pkg> build HDF5`

as suggested in https://github.com/JuliaInterop/MATLAB.jl/issues/164
