### ISSUE TITLE
Trouble loading libmx on Mavericks

### ISSUE THREAD

**Issue by rened** [JuliaInterop/MATLAB.jl#16]
I believe it was my update to Mavericks / new Xcode that broke my `MATLAB.jl` installation. Both my Matlab and my env are the same, but now I get:

```
ERROR: could not load module /Applications/MATLAB_R2011a.app/bin/maci64/libmx: dlopen(/Applications/MATLAB_R2011a.app/bin/maci64/libmx.dylib, 9): Library not loaded: libtbb.dylib
  Referenced from: /Applications/MATLAB_R2011a.app/bin/maci64/libut.dylib
  Reason: image not found
 in dlopen at c.jl:27
 in load_libmx at /Users/rene/.julia/MATLAB/src/mxbase.jl:77
 in include at boot.jl:238
 in include_from_node1 at loading.jl:114
 in include at boot.jl:238
 in include_from_node1 at loading.jl:114
 in reload_path at loading.jl:140
 in _require at loading.jl:58
 in require at loading.jl:43
at /Users/rene/.julia/MATLAB/src/mxbase.jl:85
at /Users/rene/.julia/MATLAB/src/MATLAB.jl:34
```

All the mentioned files exist, have the right permissions and even including `/Applications/MATLAB_R2011a.app/bin/maci64` in `LD_LIBRARY_PATH` makes no difference. Trying to add it to `DYLD_LIBRARY_PATH` crashes Julia during start (before `using MATLAB`).

(Un-)Setting `MATLAB_HOME` makes no difference. (Also there is only 1 Matlab installed)

Running Julia Version 0.2.0+26 (2013-11-18 19:08 UTC) and current MATLAB.jl cloned from git URL.

I think the only difference between the last-working state and now is the installation of Mavericks / Xcode updates.

Does anybody see the same behavior? Any hints very much appreciated!

**Comment by musm** [comment]
Is this still an issue?

**Comment by musm** [comment]
can someone close this, thanks

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
let's close this, if there are further issues please reopen with more detail

**Comment by musm** [comment]
bump for the close

**Comment by musm** [comment]
bump for the close

**Comment by musm** [comment]
bump for the close

**Comment by musm** [comment]
bump for the close

**Comment by musm** [comment]
close?

**Comment by musm** [comment]
@rened  I am closing this issue, since there hasn't been any action. If this is still a problem please open another issue.
