### ISSUE TITLE
ERROR: LoadError: InitError: The MATLAB library path could not be found.

### ISSUE THREAD

**Issue by OVGULIU** [JuliaInterop/MATLAB.jl#164]
Hello,

I cannot test MATLAB.jl 

error:  **ERROR: LoadError: InitError: The MATLAB library path could not be found.**

how can I fix the error?

Thanks in advance!

**Comment by musm** [comment]
do you have matlab on you system

**Comment by OVGULIU** [comment]
@musm  sure ...

**Comment by musm** [comment]
Where is matlab installed?

**Comment by musm** [comment]
If it's installed to a custom location add the `MATLAB_HOME`  environment variable with its correct location

**Comment by OVGULIU** [comment]
@musm something like:

ENV["MATLAB_HOME"] = "... path of the matlab executable ..."

is it correct???

**Comment by musm** [comment]
exactly

**Comment by OVGULIU** [comment]
@musm it does not work:ERROR: LoadError: InitError: The MATLAB library path could not be found.

**Comment by OVGULIU** [comment]
@musm I have changed the folder, however, I saw a new error:

**LoadError: UndefRefError: access to undefined reference**....

**Comment by musm** [comment]
You have to rerun
```
pkg>build HDF5
```

**Comment by OVGULIU** [comment]
Actually, this method is not working ......

**Comment by musm** [comment]
please post `versioninfo()`   also the location of your matlab installation and it's version. It's hard to help you without you helping by providing further details.

**Comment by OVGULIU** [comment]
@musm 

```
Stacktrace:
 [1] MatFile(::String, ::String) at C:\Users\david\.juliapro\JuliaPro_v1.2.0-1\packages\MATLAB\cVrxc\src\matfile.jl:8
 [2] #write_matfile#10 at C:\Users\david\.juliapro\JuliaPro_v1.2.0-1\packages\MATLAB\cVrxc\src\matfile.jl:72 [inlined]
 [3] (::getfield(MATLAB, Symbol("#kw##write_matfile")))(::NamedTuple{(:a, :b, :c, :d, :s, :ss),Tuple{Array{Int32,2},Array{Float64,1},Array{Array{Float64,1},1},Dict{String,Any},String,Array{S,1}}}, ::typeof(write_matfile), ::String) at .\none:0 [4] top-level scope at C:\Users\david\BEM\test.jl:10
in expression starting at C:\Users\david\BEM\test.jl:10
```

**Comment by musm** [comment]
> please post versioninfo() also the location of your matlab installation and it's version. It's hard to help you without you helping by providing further details.

**Comment by OVGULIU** [comment]
@musm may I ask:

1. can we use MATLAB 2019 with MATLAB.jl?

2. can we use JuliaPro 1.2.0 with MATLAB.jl?

**Comment by musm** [comment]
For 1. yes (it works on my machine)
For 2. probably and I see no reason why it wouldn't, unless JuliaPro is doing something it shouldn't
