### ISSUE TITLE
Windows new license now causes startup issues 

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaInterop/MATLAB.jl#165]
From what I can see, the session doesn't seem to stay open. Using the command prompt as administrator it works just fine. This is Windows and just started happening after changing to a new license.

```
┌ Warning: Confirm MATLAB is installed and discoverable.
└ @ MATLAB C:\Users\accou\.julia\dev\MATLAB\src\engine.jl:28
┌ Warning: Ensure `matlab -regserver` has been run in a Command Prompt as Administrator.
└ @ MATLAB C:\Users\accou\.julia\dev\MATLAB\src\engine.jl:30
```

```
MATLAB.MEngineError("failed to open MATLAB engine session")
(::MATLAB.var"#MSession#11#12")(::String, ::Type{MSession}, ::Int64) at engine.jl:34
MSession at engine.jl:23 [inlined]
MSession at engine.jl:23 [inlined]
get_default_msession at engine.jl:88 [inlined]
put_variable at engine.jl:159 [inlined]
#__solve#4(::Array{Float64,1}, ::Bool, ::Float64, ::Float64, =
etc.
```

**Comment by musm** [comment]
did you try to rebuild `MATLAB.jl` ?

**Comment by musm** [comment]
Also confirm matlab.exe starts and is functional  and also

> Start a Command Prompt as an Administrator and enter matlab /regserver.

**Comment by ChrisRackauckas** [comment]
Yeah, as mentioned from the command prompt it works just fine. Also, it doesn't seem to happen if I run the MATLABDiffEq.jl test codes first (not just the test, but also running the script). So it seems to be something related to BenchmarkTools.jl

**Comment by musm** [comment]
Hmm interesting

**Comment by musm** [comment]
closing since seems unrelated
