### ISSUE TITLE
Calling custom MATLAB function

### ISSUE THREAD

**Issue by natgeo-wong** [JuliaInterop/MATLAB.jl#171]
Hi!  I have a custom MATLAB function that I would like to call.  How do I define this custom MATLAB function in Julia?  Or alternatively if I have a `.m` file that contains the function, is it possible to point Julia to define the function based on that file?

**Comment by kongdd** [comment]
Is this problem solved?

**Comment by DNF2** [comment]
This should work by just adding the location of the function to path:
```
mat"addpath('path/to/folder')"
```
And then call the function
```
val = mat"myfunction($arg1, $arg2)"
```
