### ISSUE TITLE
Continous integration

### ISSUE THREAD

**Issue by yakir12** [JuliaInterop/MATLAB.jl#177]
Because Matlab®  is proprietary software we can't have continuous integration, tests, coverage, auto merging on General, etc. However, there has been some recent work on a workaround at https://github.com/JuliaRegistries/RegistryCI.jl/issues/283. It would be great for `MATLAB.jl` to enjoy the same benefits, but this will also benefit all the other packages that depend on `MATLAB.jl`.

**Comment by stillyslalom** [comment]
Take a look at my workaround [here](https://github.com/stillyslalom/Velocimetry.jl/blob/c191192c2cd0145a2a67ac7514f4e61a64538abd/src/Velocimetry.jl#L8-L18). It'd be great to have something like this built into MATLAB.jl. If we wanted to get fancier, we could follow the approach taken by CUDA.jl for lazy initialization (https://github.com/JuliaGPU/CUDA.jl/blob/b2ec2c0963236bbcb6774a1a73660710b0eb8ee7/src/initialization.jl).

**Comment by musm** [comment]
> but this will also benefit all the other packages that depend on MATLAB.jl.

why does it matter if  automerge works for packages that depend on MATLAB.jl ?

**Comment by yakir12** [comment]
Well, if CI fails for MATLAB.jl then CI will fail for packages that depend on MATLAB.jl. If this problem is fixed for MATLAB.jl then it'll also be fixed for all the packages that depend on MATLAB.jl.

**Comment by yakir12** [comment]
Have you seen the solution here: https://github.com/jump-dev/CPLEX.jl/pull/335 
Can something like this work for MATLAB.jl?

**Comment by musm** [comment]
I have a PR that should address this. But to be 100% clear, you want CI to be able to import MATLAB.jl even if MATLAB.jl is not correctly installed?

**Comment by musm** [comment]
In the linked PR, CI passes (which simply just confirms MATLAB is able to be imported without error even if the library does not exist on CI infrastructure)

**Comment by stillyslalom** [comment]
Another option: Mathworks seems to have developed a free (?) [GithubActions integration](https://github.com/matlab-actions/setup-matlab/#set-up-matlab). See also the Mathworks CI splash page: https://www.mathworks.com/solutions/continuous-integration.html

**Comment by musm** [comment]
Oh that would be awesome. I tried it but it can't find the `libmx.so` 

@stillyslalom are you on an Linux machine?

**Comment by stillyslalom** [comment]
Nope, Windows, but I have WSL2 set up with Ubuntu 20.04.

**Comment by musm** [comment]
I was able to get pretty far testing on Linux CI  but for some reason the engine fails
https://github.com/JuliaInterop/MATLAB.jl/pull/188/checks?check_run_id=2463413331

**Comment by musm** [comment]
If anyone could first confirm that this package works on matlab2021a that would be help in trying to pinpoint what is going on.

**Comment by musm** [comment]
I can tag a patch release with the latest changes which permit CI to import the package without failure if matlab is not installed.

**Comment by musm** [comment]
If we can figure out the matlab gh actions stuff, I can then reenable the package to permit CI testing. I think that will still integrate with external packages without any hacks?

**Comment by stillyslalom** [comment]
An environment variable might be more appropriate (`MATLAB_JL_SKIP_CI`?), since some CI environments (including private repos) won't work with Matlab's CI pipeline.

**Comment by musm** [comment]
Yes that's a good idea. So the MATLAB gh action doesn't support calling the MATLAB engine. For now I think we can close this as users can now use MATLAB.jl without custom handling.
