### ISSUE TITLE
Failed to open a MATLAB engine session on Windows

### ISSUE THREAD

**Issue by prdubois** [JuliaInterop/MATLAB.jl#23]
Hello,
When calling restart_default_msession(), I get the following error on Windows:
ERROR: MEngineError("Failed to open a MATLAB engine session.")
 in MSession at C:\Users\CAPADUB.julia\MATLAB\src\engine.jl:26

I'm using Matlab R2014a 64 bits. I tried setting the env variable MATLAB_HOME to no avail.

Any idea of what might be going on? I can start Matlab from a normal Windows command prompt.

**Comment by ChrisRackauckas** [comment]
Having the same issue here.

**Comment by musm** [comment]
Same problem here under new MATLAB2016b....

**Comment by musm** [comment]
fyi @twadleigh  I installed the new matlab and tried to give matlab.jl mexjulia all a go...even more unfortunately than before now matlab.jl doesn't work at all.... 

for some reason (I'm trying to figure it out)
https://github.com/JuliaInterop/MATLAB.jl/blob/master/src/engine.jl#L24
fails with a null pointer...

**Comment by musm** [comment]
cc https://github.com/JuliaInterop/MATLAB.jl/issues/50

**Comment by musm** [comment]
closed by: https://github.com/JuliaInterop/MATLAB.jl/pull/52
both myself and @ChrisRackauckas  confirms things now work.
@prdubois let me know if it's still a problem
