### ISSUE TITLE
Possible rename for consistency

### ISSUE THREAD

**Issue by ViralBShah** [JuliaInterop/MATLAB.jl#25]
Does it make sense to call this package `MATLABCall.jl` along the lines of various other packges such as `PyCall` and `JavaCall`? 

I presume that for Octave, we will need a separate package.

**Comment by musm** [comment]
+1 Good be a good time to do it now

**Comment by ViralBShah** [comment]
Would have done it - but I don't have rights on this org. Could someone add me as owner?

**Comment by musm** [comment]
@twadleigh Thoughts, since you mentioned you would like to incorporate your package to MATLAB.jl  ?

**Comment by twadleigh** [comment]
`MATLABCall` sounds fine, though the bit of functionality I propose to add is for the reverse. :bike: The all-caps/mixed-caps does grate a bit. Would `MatlabCall` be acceptable?

**Comment by ViralBShah** [comment]
+1 to MatlabCall.jl

**Comment by ChrisRackauckas** [comment]
Yes, it really should change to match all of the others. Is there a reason why this has stalled?

**Comment by simonbyrne** [comment]
Renaming packages in the current package system is a bit of a pain: when we renamed Stats.jl to StatsBase.jl this caused a lot of problems (it essentially breaks the setup of anyone who has it already installed, or any packages which depend on it).

A simpler way forward may be to create a new package (or fork this one) and register it under the new name, and deprecate this one.

**Comment by ChrisRackauckas** [comment]
There aren't that many issues, and the two @musm PRs should be pulled in pretty quickly. This means that moving forward with a fork would be pretty easy and nothing really would be lost. I think that's a good path to take.

**Comment by simonster** [comment]
The other option is to rename the package to MatlabCall.jl, then fork the renamed package back to MATLAB.jl. Then the issues and PRs remain attached and at least in principle nothing breaks.

**Comment by musm** [comment]
@simonster that sounds like the best option, I think we should do that.

**Comment by tkelman** [comment]
Everyone's remotes who has the package installed already won't be updated. Just leave it as is, much less hassle.

**Comment by simonster** [comment]
Yeah, I guess the other option is to leave the name as is for now and wait until there is a better way of renaming packages, which will hopefully be part of Pkg3.

**Comment by musm** [comment]
Who knows when Pkg3 will arrive, I think it's best to get these things done ASAP, instead of waiting for *years* and then nothing materializing.  This issue was opened *Dec 6, 2014*

There was a good consensus  for a rename, we should do it now.

**Comment by tkelman** [comment]
Why is now a better time? Renaming packages still works just as poorly, if anything more people have this package installed now than when this was opened.

**Comment by ViralBShah** [comment]
I think it is ok to rename the package. Do we have any stats on how many clones the package gets?

Pkg3, I expect will be before 1.0, but it is not coming next week. @StefanKarpinski can say more.

**Comment by tkelman** [comment]
44 uniques in the last 2 weeks. Pkg doesn't update remotes on existing clones, and Pkg.rm won't fix it either. Starting a new separate repo and deprecating this name is fine (but not worth the trouble IMO), but don't put a new repo in this one's place.

**Comment by ViralBShah** [comment]
Ok, that will certainly inconvenience more people than I would like to. I am ok with a new repo and deprecating this name, but we need a new active maintainer for this package at the very least then. Otherwise, may not be worth the effort.

**Comment by musm** [comment]
Closing since I think the ship has sailed on this package; in any case I think I will try to wrap the cpp MATLAB engine api and create a new package for that; so the name  in the new package can reflect the options in this issue.
