### ISSUE TITLE
Error in operator parsing

### ISSUE THREAD

**Issue by mrkulk** [JuliaInterop/MATLAB.jl#26]
Here's a simple piece of code which fails:

```
julia> @matlab begin
       a=2*2*2*2;
       end
 a = *(2, 2, 2, 2);
     |
Error: Unexpected MATLAB operator.
```

Is the parser restricted to operations on two numbers at a time? The above code is fine with explicit parenthesis around every pair of numbers.

**Comment by bellyroun** [comment]
I've met the same issue.
`@matlab 2*2` will return the correct answer, but `@matlab 2*2*2` won't. 
It seems that `2*2*2` was parsed into `*(2,2,2)`, which is correct for Julia, but not correct for MATLAB.
A quick and dirty workaround is to add more parenthesis, for example `@matlab (2*2)*2` will give you the right answer.

**Comment by simonster** [comment]
This will work with the new [mat string literal](https://github.com/JuliaLang/MATLAB.jl#the-mat-custom-string-literal).

**Comment by musm** [comment]
close?

**Comment by simonster** [comment]
Well, it's not fixed AFAIK. But we could just deprecate the `@matlab` macro. Trying to rewrite the Julia AST to make it valid MATLAB was probably not the right approach.

**Comment by musm** [comment]
Ok probably best to deprecate then, the package is already so broken I doubt any will care.

**Comment by ChrisRackauckas** [comment]
The string macro seems safer and more expressive, so it's probably best to deprecate the `@matlab` macro since it's essentially just a trap. Is there any case where it's better than using `mat""`?

**Comment by musm** [comment]
Or better just make `@mat`   wrap to the `mat""` string macro

**Comment by musm** [comment]
closed, `@matlab` has been deprecated in favor of `mat"..."`
