### ISSUE TITLE
MATLAB.jl does not work with MATLAB 2016b on linux/windows

### ISSUE THREAD

**Issue by musm** [JuliaInterop/MATLAB.jl#50]
I tested both linux and windows and MATLAB.jl fails to open a MATLAB engine session.

**Comment by musm** [comment]
`matlab /regserver`  has to be done on an admin cmd prompt.

I'm not sure what the corresponding fix for linux would be

@twadleigh

**Comment by ChrisRackauckas** [comment]
@musm's fix finally gets this working on Windows. It should be added to the installation instructions.
