### ISSUE TITLE
Tag a new version?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaInterop/MATLAB.jl#51]
The last tag is really old and won't work anymore because of an error looking for `UInt32`.

**Comment by musm** [comment]
I'm thinking of updating the package but dropping v0.4 support. Thoughts?

**Comment by ChrisRackauckas** [comment]
Yes

**Comment by ChrisRackauckas** [comment]
I was able to push the tags. It's in METADATA right now: https://github.com/JuliaLang/METADATA.jl/pull/6903

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/6904
