### ISSUE TITLE
myriad ways to segfault

### ISSUE THREAD

**Issue by musm** [JuliaInterop/MATLAB.jl#58]
```
x = mxarray(1.0)
delete(x)
jvariable(x)
```
calling any MATLAB.jl function on `x` will segfault.

**Comment by ChrisRackauckas** [comment]
It's clear this will cause problems and is user error, but is there a way to stop it from segfaulting? It's not clear to me how you'd stop it.

**Comment by musm** [comment]
Yes it is possible to prevent segfault. I need to submit PR, for this.

**Comment by musm** [comment]
It's not really user error, the code right now is broken...  It shouldn't segfault on a deleted reference...

**Comment by ChrisRackauckas** [comment]
The PR is adding a check for whether the reference still exists before using it? How much overhead does that add?
