### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by musm** [JuliaInterop/MATLAB.jl#89]
Since the last tag there have been many segfault fixes (i.e. on the latest tag it's still very easy to segfault `MATLAB.jl` ) and library improvements. I'm now aware of only one possible way to segfault (edit: I'm having a hard time reproducing the segfaults I used be able to generate here) matlab if it's used interactively (see https://github.com/JuliaInterop/MATLAB.jl/issues/84)
I think it would make sense to tag a new release soon.

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
@simonster @ChrisRackauckas  

the only issue I would like a fix for is https://github.com/JuliaInterop/MATLAB.jl/issues/95 but that is a bug fix

**Comment by ChrisRackauckas** [comment]
When #95 is fixed that could just be a patch.

**Comment by ChrisRackauckas** [comment]
I can't push tags, so someone else would have to.

**Comment by musm** [comment]
What's the objection of tagging?

**Comment by musm** [comment]
bump

**Comment by musm** [comment]
@ChrisRackauckas weren't you able push tags before?
@tkelman

**Comment by tkelman** [comment]
You should have write access?

**Comment by ChrisRackauckas** [comment]
Ahh, I had cloned it with the wrong protocol before so it just wasn't authenticating correctly. I was able to push a tag. My bad!

**Comment by ChrisRackauckas** [comment]
The PR is in, we can handle any further discussion on this there.

**Comment by musm** [comment]
Thanks again
