### ISSUE TITLE
Passing functions to MATLAB

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaInterop/MATLAB.jl#98]
Is there a way using MATLAB.jl to pass functions or anonymous functions to MATLAB?

**Comment by musm** [comment]
@twadleigh mexjulia package https://github.com/twadleigh/mexjulia allows you to call julia function's from matlab, we can probably then marshall that back to the julia terminal

**Comment by twadleigh** [comment]
I suspect the engine interface on which MATLAB.jl is based isn't sufficiently rich by itself to support that. 

That sort of thing, of course, is possible with [mexjulia](https://github.com/twadleigh/mexjulia), but the matlab/julia relationship is different than for MATLAB.jl. For mexjulia, they occupy the same address space and matlab is primarily in charge. 

The other call-julia-from-matlab project out there is [julia-matlab](https://github.com/timholy/julia-matlab), which is an out-of-process bridge between the two with communication provided by zeromq. That basic concept could be made to work in the MATLAB.jl context, but that project is well out of date and would require a good deal of work to satisfy this use case.

I might potentially be interested in helping to get julia-matlab functional again, as certain still mysterious issues (see, _e.g._, https://github.com/JuliaLang/julia/issues/19437) related to embedding julia hamper my confidence that mexjulia can be declared stable enough for general use (although it has been stable enough for me to do real work with it lately).

**Comment by ChrisRackauckas** [comment]
My need is actually really simple: I just want to pass the anonymous function over to MATLAB inside of a `m_session()` to then call `ode45` or what not with it. What I am trying to do is:

1. Passing the data for the differential equation
2. Passing the function
3. Call `ode45` on these things and the function handle for the function I just sent over (from Julia)
4. Pull the solution back to Julia

I have every step together except 2.

[Basically, I am writing a package which adds the MATLAB differential equation solvers to JuliaDiffEq to be able to benchmark them.]

**Comment by twadleigh** [comment]
And making the thing to pass in step 2 is precisely the hard part. It needs, presumably, to be an anonymous matlab function, which can't be made on the C/Julia side of the `libmx` interface, so would need to be constructed using matlab code. But to create such a thing, you need a way to call into julia from matlab, and that doesn't readily exist in the `MATLAB.jl` context.

**Comment by musm** [comment]
one hacky way  if this is urgent, is if the function can be easily converted to  valid matlab syntax is write a macro that converts it to a valid matlab function definition and pass it as a string that can be evaluated by matlab?

**Comment by ChrisRackauckas** [comment]
It's not urgent. I would just like a package that makes it easy to run the MATLAB ode functions so that way we can easily run benchmarks and once again show why you shouldn't use MATLAB. But what's nice about your solution for this case is that it would create an actual MATLAB function, which would better indicate MATLAB's real performance.

**Comment by twadleigh** [comment]
If what you are really after is benchmarks, wouldn't the need to marshal data back and forth across the process boundary at every function call cloud the meaningfulness, anyway?

**Comment by ChrisRackauckas** [comment]
Yeah. Actually, I can probably just build the string for the function to send to MATLAB since I have the function's definition available. Are anonymous functions handles still treated differently (slowly) in that world?

**Comment by ChrisRackauckas** [comment]
Since my functions are described in a special way ([ParameterizedFunctions.jl](https://github.com/JuliaDiffEq/ParameterizedFunctions.jl)), I was able to write a way to build an anonymous function directly in MATLAB and use that for [MATLABDiffEq.jl](https://github.com/JuliaDiffEq/MATLABDiffEq.jl). So while that covers my use case, it's very specific. It would be hard to generalize too because more general functions can very in syntax (loops "might usually" look like MATLAB, but "proper" loops usually shouldn't do `for i in 1:length(x)`, rather they should do `for i in eachindex(x)`, etc., which would make it really difficult to parse a function and write the appropriate MATLAB anonymous function). Also anonymous functions in MATLAB can only have one expression (cannot be multi-line), so this is far too restrictive for other use cases. 

So it seems that calling into Julia from MATLAB is required to actually do this due to the restrictions of anonymous function definitions in MATLAB, meaning that this functionality won't be possible with this package. That said, mexjulia is one package that can handle this. But as @twadleigh mentions, it will have to do data transfers, which may make this costly. 

Because of this, it seems outside the scope of the package, so I am closing this issue.
